name: Action Sample

on:
  push:
    branches: 
      - master
      - develop
      - '**'        # matches every branch
  pull_request:  
    types: [opened]  
  workflow_dispatch:

jobs:
  run-sampleData-test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2.4.3
      - name: Setup Python
        uses: actions/setup-python@v2.4.3
        with:
          python-version: '3.11'
          architecture: 'x64'
      - name: pip install
        run: pip install -r requirements.txt
      - name: test cicd
        run: python -m pytest ./web-test.py 
      # - name: Run develop scripts
      #   run: python test_ginza.py        
